version: '3'

services:
  security-test:
    build:
      context: ./securitytest
      dockerfile: Dockerfile
    volumes:
      - ./ssl:/etc/kafka/secrets
    networks:
      - kafka-network
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_SSL_CAFILE: /etc/kafka/secrets/ca.crt
      KAFKA_SSL_CERTFILE: /etc/kafka/secrets/client.crt
      KAFKA_SSL_KEYFILE: /etc/kafka/secrets/client.key
      KAFKA_SASL_MECHANISM: PLAIN
      KAFKA_SASL_USERNAME: wrong_username
      KAFKA_SASL_PASSWORD: wrong_password
    command: ["python", "main.py"]

networks:
  kafka-network:
    name: kafka_test_kafka-network
    external: true